name: Deploy Multidocker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t b3rcikfm/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true b3rcikfm/react-test npm test # CI=true is a common convention to indicate that the application is running in a continuous integration environment
      
      - run: docker build -t b3rcikfm/multi-client ./client
      - run: docker build -t b3rcikfm/multi-nginx ./nginx
      - run: docker build -t b3rcikfm/multi-server ./server
      - run: docker build -t b3rcikfm/multi-worker ./worker

      - run: docker push b3rcikfm/multi-client:latest
      - run: docker push b3rcikfm/multi-nginx:latest
      - run: docker push b3rcikfm/multi-server:latest
      - run: docker push b3rcikfm/multi-worker:latest
